# Generated by Django 5.0.6 on 2024-06-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'Customer Address', 'verbose_name_plural': 'Customer Addresses'},
        ),
    ]
