# Generated by Django 5.0.6 on 2024-06-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_customeraddress_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRetingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('review', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ratings', to='main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='main.product')),
            ],
            options={
                'verbose_name': 'Product Reting Review',
                'verbose_name_plural': 'Product Retings Reviews',
            },
        ),
    ]
